### ISSUE TITLE
Flarum Login Dialog on reply/start discussion

### ISSUE THREAD

**Issue by dartrax** [AlexanderOMara/flarum-wp-users#1]
When I click "sign in" or "register", the Wordpress login dialog gets displayed. But when I click "start discussion" instead or try to reply in an existing discussion, the flarum login window appears. Shouldn't that never be displayed once this extension gets activated?

Not sure if actually an issue because I may not have set it up correctly yet. But before I put more efforts in the setup (moving my current flarum testing env from http://localhost/flarum/ to http://localhost/wordpress-directory/flarum/ and removing public folder) I'd like to know if this is a bug and if it can be fixed ;-)

**Comment by AlexanderOMara** [comment]
Sorry for the delay, GitHub didn't send me a notification for some reason.

Yes, looks like there are more ways to open the dialog than I initially realized. I'm looking into the best way to improve this.

**Comment by dartrax** [comment]
Thank you for looking into it! I'm currently testing another extension with the same goal but different approach. As of now, it has [several issues](https://discuss.flarum.org/d/21666-php-and-wordpress-single-sign-on-sso/265), so it would be great to have an alternative way to do this.

**Comment by AlexanderOMara** [comment]
5625ecf16f8ef76b4ec6afeff8c874dacb50721b should take care of any remaining ways of opening the login dialog.

After a bit of maintenance I'll release an update.

**Comment by AlexanderOMara** [comment]
Just released version 1.0.2 which includes this fix.

**Comment by dartrax** [comment]
Thanks! I get a console error when I'm in admin interface:
![image](https://user-images.githubusercontent.com/15105943/88485654-c0bea980-cf77-11ea-9a44-85c4e438a84b.png)
![image](https://user-images.githubusercontent.com/15105943/88485680-f5cafc00-cf77-11ea-9b26-4c11f00eb5d7.png)

**Comment by AlexanderOMara** [comment]
Thanks! Turns out `LogInModel` is `undefined` in the admin panel. A simple fix now available in version 1.0.3.

**Comment by dartrax** [comment]
That was quick! Fixed 👍
