### ISSUE TITLE
when redirected, flarum is failed to login in

### ISSUE THREAD

**Issue by BeyondIM** [AlexanderOMara/flarum-wp-users#3]
I'm use flarum v0.1.0-beta.13.

When I click "sign in", the Wordpress login dialog gets displayed. Then when I input user info and login in, it redirect to flarum, but flarum is failed to login in and show as login out status. tks.

**Comment by AlexanderOMara** [comment]
I've tested it with Flarum v0.1.0-beta.12 to v0.1.0-beta.13 and WordPress 5.4.2 to 5.5.1 and everything should still be working.

Some troubleshooting:
- Is the Flarum site on the same domain as the WordPress site so it can see the WordPress cookie?
- Does the user that isn't logged out exist on the Flarum site yet? If not, does another not-managed user have that name but a different email address?

**Comment by BeyondIM** [comment]
wp site: https://example.com
flarum site: https://example.com/forum

I use caddy as web server

```
// caddy config file
example.com {
    gzip
    root /var/www/html
    fastcgi / wordpress_app:9000 php
    rewrite / {
        if {path} not_match ^\/wp-admin
        to {path} {path}/ /index.php?{query} 
    }
    rewrite /forum {
        to {path} {path}/ /forum/index.php?{query} 
    }
}
```

![2020-09-05_13-18.png](https://i.loli.net/2020/09/05/gWboQNm7GrpzInc.png)

![2020-09-05_13-30.png](https://i.loli.net/2020/09/05/B632dUjET9V4qWh.png)

**Comment by AlexanderOMara** [comment]
The Cookie Name is not correct:
```
wordpress_logged_in_*
```

The real cookie name will start with `wordpress_logged_in_` followed by an MD5 hash, something like this:
```
wordpress_logged_in_0123456789abcdef0123456789abcdef
```

Check your browser's developer tools for what that cookie is named on your site.

**Comment by BeyondIM** [comment]
It work perfect now. Thank you for the great work. :100:
