### ISSUE TITLE
flarum beta 14 compatibility

### ISSUE THREAD

**Issue by dartrax** [AlexanderOMara/flarum-wp-users#4]
Hi,
will this extension be compatible with beta 14?
Right now, Extiverse states 

> INCOMPATIBLE WITH FLARUM 0.1.0-BETA.14

Thank you for your great work!

**Comment by AlexanderOMara** [comment]
It will be if it isn't already. I'll look into it this weekend.

**Comment by AlexanderOMara** [comment]
Had to make a couple of changes, but version 1.1.0 is now available supporting Flarum Beta 14.

**Comment by dartrax** [comment]
Great! I‘ll test as soon as i‘m able to update everything to beta 14!  Thank you 😊
