### ISSUE TITLE
flarum beta 15 Fatal error: Trait 'Flarum\User\AssertPermissionTrait' not found in AddUserSaving.php

### ISSUE THREAD

**Issue by dartrax** [AlexanderOMara/flarum-wp-users#6]
As soon as I enable this plugin in flarum, I get a blank page with this line:
`Fatal error: Trait 'Flarum\User\AssertPermissionTrait' not found in C:\xampp\htdocs\flarum\vendor\alexanderomara\flarum-wp-users\src\Listener\AddUserSaving.php on line 14`

Flarum is no longer working, I needed to rename `\htdocs\flarum\vendor\alexanderomara\flarum-wp-users` to be able to access flarum again and disable the plugin.

**Comment by AlexanderOMara** [comment]
Looks like the [AssertPermissionTrait](https://api.docs.flarum.org/php/master/flarum/user/assertpermissiontrait) API was deprecated and removed. Will have to make an update.

**Comment by AlexanderOMara** [comment]
Just released version 1.2.0 which should take care of Flarum Beta 15 compatibility.

Let me know if you find any more issues!

**Comment by dartrax** [comment]
Quick as always! Many thanks!! 👍
